Table "product" {
  "id" bigint [pk, not null, increment]
  "name" varchar(20) [not null]
  "price" int [not null]
  "createdAt" datetime [not null, default: `current_timestamp()`]
  "updatedAt" datetime [not null, default: `current_timestamp()`]
  "deletedAt" datetime
}